version: 2

jobs:
  build:
    docker:
      # node-browsers come with java pre-installed
      - image: circleci/php:5.6-node-browsers
    working_directory: ~/openzipkin
    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run: composer install -n --prefer-dist
      - run: curl -sSL https://zipkin.io/quickstart.sh | bash -s

      # install kafka
      - run: curl -SL http://archive.apache.org/dist/kafka/0.8.2.2/kafka_2.11-0.8.2.2.tgz | tar xz
      - run:
          background: true
          command: bash -c "cd kafka_* && bin/zookeeper-server-start.sh config/zookeeper.properties >/dev/null 2>&1 &"
      - run:
          background: true
          command: bash -c "cd kafka_* && bin/kafka-server-start.sh config/server.properties >/dev/null 2>&1 &"
      # run zipkin
      - run:
          background: true
          command: java -jar zipkin.jar
      # block until zipkin is available
      - run: wget --retry-connrefused -T 60 -O /dev/null http://127.0.0.1:9411/health
      # start both processes in the background, but don't use composer as it dies
      - run:
          background: true
          command: php -S '127.0.0.1:8081' frontend.php
      - run:
          background: true
          command: php -S '127.0.0.1:9000' backend.php
      # hit the frontend which calls the backend
      - run: wget -v --retry-connrefused -T 5 -O /dev/null 127.0.0.1:8081
      - run: |
          # wait just in case
          sleep 1
          test $(curl -s 127.0.0.1:9411/api/v2/traces | jq '.[0] | length') -eq 4

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - beta
    jobs:
      - build
