version: 2

jobs:
  build:
    docker:
      - image: circleci/php:5.6-cli
    working_directory: ~/openzipkin
    steps:
      - checkout
      - run: sudo composer self-update
      - run: composer install -n --prefer-dist
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker run -d --name zipkin -p 9411:9411 openzipkin/zipkin
          docker exec zipkin curl -s --retry 10 --retry-delay 5 --retry-connrefused http://127.0.0.1:9411/health
      - run:
          background: true
          command: composer run-frontend
      - run:
          background: true
          command: composer run-backend
      - run: bash test.sh
